name: conduit_interview_task
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/sk0x0y/conduit_interview_task

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  get_it: ^7.7.0
  mockito: ^5.4.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
